general.import = ["~/.cache/wal/colors-alacritty.toml"]
[window]

opacity = 0.5

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Noto Sans Mono"
bold.family = "Noto Sans Mono"
italic.family = "Noto Sans Mono"
bold_italic.family = "Noto Sans Mono"

size = 10.0


# [colors.primary]
# background = "#0e1a24"  # –û—á–µ–Ω—å —Ç—ë–º–Ω—ã–π —Å–∏–Ω–µ-—á—ë—Ä–Ω—ã–π (–ø–æ—á—Ç–∏ –Ω–æ—á—å)
# foreground = "#dceeff"  # –°–≤–µ—Ç–ª—ã–π –≥–æ–ª—É–±–æ–≤–∞—Ç–æ-–±–µ–ª—ã–π (—Ç–µ–∫—Å—Ç)

# [colors.cursor]
# text = "#0e1a24"
# cursor = "#3392f5"  # –û—Å–Ω–æ–≤–Ω–æ–π –≥–æ–ª—É–±–æ–π

# [colors.normal]
# black   = "#0e1a24"  # –¢—ë–º–Ω—ã–π —Ñ–æ–Ω
# red     = "#f15b6c"  # –ú—è–≥–∫–∏–π –∫–æ—Ä–∞–ª–ª–æ–≤–æ-–∫—Ä–∞—Å–Ω—ã–π
# green   = "#67d2a4"  # –ê–∫–≤–∞–º–∞—Ä–∏–Ω–æ–≤–æ-–∑–µ–ª—ë–Ω—ã–π
# yellow  = "#f0c674"  # –ó–æ–ª–æ—Ç–∏—Å—Ç–æ-–∂—ë–ª—Ç—ã–π
# blue    = "#3392f5"  # üí† –û—Å–Ω–æ–≤–Ω–æ–π –≥–æ–ª—É–±–æ–π
# magenta = "#bd93f9"  # –°–≤–µ—Ç–ª–æ-—Ñ–∏–æ–ª–µ—Ç–æ–≤—ã–π
# cyan    = "#50d8eb"  # –Ø—Ä–∫–∏–π –≥–æ–ª—É–±–æ–π —Å —É–∫–ª–æ–Ω–æ–º –≤ –±–∏—Ä—é–∑—É
# white   = "#dceeff"  # –°–≤–µ—Ç–ª—ã–π –≥–æ–ª—É–±–æ–π –±–µ–ª—ã–π

# [colors.bright]
# black   = "#1a2a3c"
# red     = "#ff6e7d"
# green   = "#85e7ba"
# yellow  = "#ffdd88"
# blue    = "#5aaeff"  # –ë–æ–ª–µ–µ –º—è–≥–∫–∏–π –≥–æ–ª—É–±–æ–π
# magenta = "#cfa6ff"
# cyan    = "#7fefff"
# white   = "#ffffff"



